FT_DPCM_PTR=$c000
;this file for FamiTone2 library generated by text2data tool
	.export _beach_shertigan_data
_beach_shertigan_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; 00 : Song 1

@instruments:
	.byte $30 ; 00 : Acoustic Grand Piano
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@song0ref4:
	.byte $f9, $f9, $f9, $f9, $f9, $95, $f9, $f9, $f9, $f9, $f9, $95, $f9, $f9, $f9, $f9, $f9, $95
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $f9, $f3, $80, $3a, $c3, $00, $85
@song0ref63:
	.byte $44, $a1, $01, $52
@song0ref67:
	.byte $a1, $01, $5c, $a1, $01
@song0ref72:
	.byte $52, $9f, $01, $44, $a1, $01, $52, $a1, $01, $5c, $a1, $01, $60, $9f, $00, $81, $3a, $a1, $01, $48, $a1, $01, $52, $a1
	.byte $01, $48, $9f, $01, $3a, $a1, $01, $48, $a1, $01, $52, $a1, $01, $56
@song0ref110:
	.byte $9f, $01, $40, $a1, $01, $4e, $a1, $01, $58, $a1, $01, $4e, $9f, $01, $40, $a1, $01, $4c, $a1, $01, $58, $a1, $01, $60
	.byte $9f, $00, $81
	.byte $ff, $17
	.word @song0ref63
	.byte $01
	.byte $ff, $31
	.word @song0ref63
@song0ref144:
	.byte $3a, $a1, $01, $48, $a1, $01, $52, $a1, $01, $56, $9f, $01, $5a, $c5, $00, $85, $60, $c3, $00, $85, $44, $a1, $01, $52
	.byte $a1, $01, $5c, $a1, $01, $60, $9f, $01, $44, $a5, $60
	.byte $ff, $11
	.word @song0ref67
	.byte $ff, $22
	.word @song0ref72
	.byte $3a, $a1, $01, $3e
	.byte $ff, $1b
	.word @song0ref110
	.byte $ff, $17
	.word @song0ref63
	.byte $01
	.byte $ff, $31
	.word @song0ref63
@song0ref199:
	.byte $52, $c5, $00, $85, $5a, $c3, $00, $85, $52, $c5, $00, $85, $56, $c3, $00, $85, $52, $a5
@song0ref217:
	.byte $52, $a1, $01, $5c, $f9, $ef, $36, $a1, $01, $44, $a1, $01, $56, $a1, $01, $44, $9f, $01, $3a, $a1, $01, $48, $a1, $01
	.byte $5a, $a1, $01, $48, $9f, $00, $81, $2c, $a5, $52, $a1, $01, $60, $a1, $01, $64, $9f, $01, $26, $a5, $4c, $a1, $01, $5a
	.byte $a1, $01, $5c
@song0ref268:
	.byte $9f, $01, $36, $a1, $01, $44, $a1, $01, $52, $a1, $01, $56, $9f, $01, $3a, $a1, $01, $48, $a1, $01, $56, $a1, $01, $5a
	.byte $9f, $00, $81, $44, $a1, $01, $52, $a1, $01, $60, $a1, $01, $64, $9f, $01, $3a, $a5, $48, $a1, $01, $4c, $a1, $01, $52
	.byte $ff, $27
	.word @song0ref268
	.byte $3e, $a1, $01, $52, $a1, $01, $6a, $a1, $01, $64
	.byte $ff, $0e
	.word @song0ref268
	.byte $48, $c5, $00, $85, $38, $c3, $00, $85, $3a, $f9, $91, $00, $8d, $22, $f9, $8f, $00, $8f
	.byte $ff, $4a
	.word @song0ref63
	.byte $ff, $17
	.word @song0ref63
	.byte $01
	.byte $ff, $31
	.word @song0ref63
	.byte $ff, $1e
	.word @song0ref144
	.byte $99, $53, $5c, $83, $64, $f9, $91, $00, $8d
	.byte $ff, $4a
	.word @song0ref63
	.byte $ff, $17
	.word @song0ref63
	.byte $01
	.byte $ff, $31
	.word @song0ref63
	.byte $ff, $20
	.word @song0ref144
	.byte $64, $a1, $01, $60
	.byte $ff, $11
	.word @song0ref67
	.byte $ff, $25
	.word @song0ref72
	.byte $3e
	.byte $ff, $1b
	.word @song0ref110
	.byte $ff, $17
	.word @song0ref63
	.byte $01
	.byte $ff, $31
	.word @song0ref63
	.byte $ff, $10
	.word @song0ref199
	.byte $44, $a1, $01
	.byte $ff, $63
	.word @song0ref217
	.byte $ff, $27
	.word @song0ref268
	.byte $3e, $a1, $01, $52, $a1, $01, $6a, $a1, $01, $64
	.byte $ff, $0e
	.word @song0ref268
	.byte $36, $c5, $00, $85, $50, $c3, $00, $85, $3a, $f9, $91, $00, $8d, $3a, $f9, $8f, $00, $8f
	.byte $ff, $4a
	.word @song0ref63
	.byte $ff, $17
	.word @song0ref63
	.byte $01
	.byte $ff, $31
	.word @song0ref63
	.byte $ff, $1e
	.word @song0ref144
	.byte $99, $53, $5c, $83, $64, $f9, $91, $00, $f9, $f9, $d5, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $f9, $f3, $80
@song0ref480:
	.byte $74, $a1, $01, $78, $9f, $01
@song0ref486:
	.byte $6a
@song0ref487:
	.byte $e7, $00, $8b, $78, $8f, $00, $74, $8d, $00, $72, $c5, $00, $85, $6e, $c3, $00, $85, $78, $f9, $91, $00, $dd, $78, $a1
	.byte $01, $7c, $9f, $01, $7e, $f5, $02, $9f, $01, $7c, $c5, $00, $85, $78, $c3, $00, $85, $6a, $f9, $91, $00, $dd
	.byte $ff, $1c
	.word @song0ref480
@song0ref536:
	.byte $cd, $74, $85, $78, $9f, $00, $8b, $74, $9f, $01, $72, $e7, $00, $8b, $74, $8f, $00, $72, $8d, $00, $6e, $c5, $00, $85
@song0ref560:
	.byte $72, $c3, $00, $85, $64, $f9, $91, $00, $dd, $6a, $c3, $00, $85, $7c
	.byte $ff, $25
	.word @song0ref487
	.byte $70, $c3, $00, $85, $6a, $f9, $91, $00, $dd, $74, $a1, $01, $78, $9f, $01, $7c
	.byte $ff, $15
	.word @song0ref487
	.byte $cd, $74, $85, $78, $9f, $00, $8b, $74, $9f, $01, $72
@song0ref607:
	.byte $c5, $00, $85, $7c, $a1, $01, $7e, $9f, $01, $72, $a5, $78, $a1, $01, $66, $a5
@song0ref623:
	.byte $72, $9f, $00, $81, $74, $f9, $91, $00, $b5, $74, $a1, $01
@song0ref635:
	.byte $7c, $a1, $01, $02, $9f, $01, $06, $e7, $00, $8b, $02, $8f, $00, $7e, $8d, $00, $7c, $c5, $00, $85, $78, $c3, $00, $85
	.byte $02, $e7, $00, $8b, $7c, $8f, $00, $78, $8d, $00, $74, $f9, $91, $00, $8d, $6e, $c5, $00, $85, $7e, $c3, $00, $85, $7c
	.byte $a1, $01, $78, $a1, $01, $74, $a1, $01, $78, $9f, $00, $81, $7c, $e7, $00, $8b, $7e, $8f, $00, $7c, $8d, $00, $78, $c5
	.byte $00, $85
	.byte $ff, $19
	.word @song0ref635
@song0ref712:
	.byte $c5, $00, $85, $0a, $c3, $00, $85, $0c, $a1, $01, $02, $a1, $01, $7c, $a1, $01, $74, $9f, $01, $78, $e7, $00, $8b, $78
	.byte $9f, $01, $78, $b9, $7c, $b9, $7e, $8f, $00, $91, $02, $c5, $00, $85, $66, $c3, $00, $85, $64, $c5, $00, $85, $60, $c3
	.byte $00, $85
	.byte $ff, $13
	.word @song0ref486
@song0ref765:
	.byte $cd, $0a, $a1, $01, $0c, $9f, $01, $0a, $c5, $00, $85, $78, $a1, $01, $7c, $9f, $01, $78, $e7, $00, $8b, $02, $9f, $01
	.byte $7c, $c5, $00, $85, $70, $a1, $00, $a7, $7c, $f9, $91, $00, $dd, $74, $a1, $01, $78, $9f, $01, $7c
	.byte $ff, $12
	.word @song0ref487
@song0ref812:
	.byte $cd, $0a, $a1, $01, $0c, $9f, $01, $0a, $bd, $74, $85, $78, $9f, $00, $8b, $74, $9f, $01, $72, $cd, $74, $a3, $00, $74
	.byte $8f, $00, $6e, $8d, $00, $6a, $cb, $00
	.byte $ff, $0e
	.word @song0ref560
	.byte $ff, $1c
	.word @song0ref487
	.byte $78, $e7, $00, $8b, $02, $9f, $01
@song0ref857:
	.byte $66, $c5, $00, $85, $70, $a1, $00, $a7, $6a, $f9, $91, $00, $dd, $74, $a1, $01, $78, $9f, $01, $7c
	.byte $ff, $15
	.word @song0ref487
	.byte $ff, $18
	.word @song0ref536
	.byte $6a, $c3, $00, $85, $64, $f9, $91, $00, $dd, $6a, $c3, $00, $85
	.byte $ff, $1d
	.word @song0ref486
	.byte $78, $e7, $00, $8b, $02, $9f, $01, $7c, $c5, $00, $85, $78, $c3, $00, $85, $7c, $f9, $91, $00, $dd, $74, $a1, $01, $78
	.byte $9f, $01, $7c
	.byte $ff, $15
	.word @song0ref487
	.byte $cd, $74, $85, $78, $9f, $00, $8b, $74, $9f, $01, $6a
	.byte $ff, $0e
	.word @song0ref607
	.byte $74, $a1, $01
	.byte $ff, $56
	.word @song0ref623
	.byte $ff, $19
	.word @song0ref635
	.byte $ff, $22
	.word @song0ref712
	.byte $6a, $c5, $00, $85, $66, $c3, $00, $85, $64, $c5, $00, $85, $78, $c3, $00, $85
	.byte $ff, $13
	.word @song0ref486
	.byte $ff, $18
	.word @song0ref765
	.byte $ff, $14
	.word @song0ref857
	.byte $ff, $12
	.word @song0ref487
	.byte $ff, $1a
	.word @song0ref812
	.byte $72, $8d, $00, $6a, $cb, $00, $72, $c3, $00, $85, $74, $f9, $91, $00, $f9, $f9, $f9, $f9, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref4
	.byte $fd
	.word @song0ch4loop
